version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    # Group all updates to PIP dependencies into a once-weekly PR
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    groups:
      pip-dependencies:
        applies-to: version-updates
        update-types: [minor, patch]
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    groups:
      github-action-dependencies:
        applies-to: version-updates
        update-types: [minor, patch]
        patterns:
          - '*'
