language: python
dist: bionic
matrix:
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.9"
    - python: "pypy3"
install:
  - "pip install --upgrade setuptools"
  - "pip install -r requirements.txt"
  - "pip install ."
script: py.test
