language: python
dist: xenial
matrix:
  include:
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "pypy"
    # https://github.com/travis-ci/travis-ci/issues/9542
    # pypy3 < 6.0.0 fails due to discrepancies with decimal...
    #- python: "pypy3"
install:
  - "pip install --upgrade setuptools"
  - "pip install -r requirements.txt"
  - "pip install ."
script: py.test
