language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

matrix:
  include:
  - env: COVERAGE=1
    python: "2.7"

install:
  - "pip install -r requirements.txt"
  - "pip install ."
script:
  - if [ -z $COVERAGE ] ; then
      py.test;
    else
      py.test --cov --cov-report xml && python-codacy-coverage;
    fi
