import cbor2


class CborLoadDump:
    """
    Wrapper for simpleion API that holds some configuration so that the configuration can be encapsulated here instead
    of having to be plumbed through the whole benchmark code.

    Results of profiling indicate that this adds a trivial amount of overhead, even for small data. If Ion Python
    performance improves by >1000% from June 2023, then this may need to be re-evaluated.
    """

    @classmethod
    def load(self, fp):
        while True:
            try:
                yield cbor2.load(fp)
            except EOFError:
                return

    @classmethod
    def loads(self, s):
        return cbor2.loads(s)

    @classmethod
    def dump(self, obj, fp):
        """
        The given obj must be a list generated by benchmark-cli write command that holds all top-level objects
        """
        for v in obj:
            cbor2.dump(v, fp)

    @classmethod
    def dumps(self, obj):
        for v in obj:
            cbor2.dumps(v)
