import cbor2


class Cbor2LoadDump:
    def __init__(self):
        pass

    def load(self, fp):
        while True:
            try:
                yield cbor2.load(fp)
            except EOFError:
                return

    def loads(self, s):
        return cbor2.loads(s)

    def dump(self, obj, fp):
        """
        The given obj must be a list generated by benchmark-cli write command that holds all top-level objects
        """
        for v in obj:
            cbor2.dump(v, fp)

    def dumps(self, obj):
        for v in obj:
            cbor2.dumps(v)
