import json


class JsonLoadDump:
    @classmethod
    def load(self, fp):
        while True:
            line = fp.readline()
            if line == '':
                return
            yield json.loads(line)

    @classmethod
    def loads(self, s):
        return json.loads(s)

    @classmethod
    def dump(self, obj, fp):
        """
        The given obj must be a list generated by benchmark-cli write command that holds all top-level objects
        """
        for top_level_obj in obj:
            json.dump(top_level_obj, fp)

    @classmethod
    def dumps(self, obj):
        json.dumps(obj)
